# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Install dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy project files
COPY pyproject.toml .
COPY src ./src
COPY README.md .
COPY TOOLS.md .

# Install the package
RUN pip install --no-cache-dir .

# Expose port for SSE if needed (default FASTMCP_PORT=8000)
EXPOSE 8000

# Default command: stdio transport
CMD ["logi-mcp-server", "stdio"]